grade:
  image: eu.gcr.io/shad-ts/grader/py
  only:
    - /^submits/.*$/
  script:
    - export CI_TASK_NAME=$(echo $CI_BUILD_REF_NAME | sed -e 's/submits\///g')
    - cp -r $CI_TASK_NAME /opt/shad/private/
    - cd /opt/shad/private
    - chmod -R 777 /opt/shad/private/$CI_TASK_NAME
    - cp ../.deadlines.yml ./
    - python3 grade.py grade
