WIKI_PAGE_DEPTHS = {'Sherutni_patrin': 0, 'Lekh': 1, 'Styago le romengo': 1, 'Roma': 1, 'Romani chib': 1,
                    'Standardizuimi Romani chib': 1, 'Romano lekhipen': 1, 'Chiba le romenge': 1,
                    'Patrinipen le bare Romengo': 1, 'Romano siklyaripen': 1, 'Kale': 1, 'Sinti': 1, 'Poraimos': 1,
                    'Pativ': 1, 'Desi': 1, 'Banjara': 1, 'Devnagrī': 1, 'Janglimata uchya thaj sundalutne': 1,
                    'Chexanipen': 1, 'Janglimata manushikane, puranipen,phuvipen': 1, 'Phuvipen': 1, 'Sikavdimos': 1,
                    'Tehnologia thaj janglimata thodine': 1, 'Compyutereske janglimata': 1,
                    'Devlesko janglipen, uchioshukaripen, lekhavipen, shiba': 1, 'Shibavipen': 1,
                    'Chailipo thaj manushikanipo': 1, 'Index': 1, 'Jivaniakohramovipen': 1, 'I sherutni pajina': 1,
                    'Bibarilo lekh': 2, '1971': 2, 'Mashkarthemutno Romano Kongreso': 2, 'Romane manusha': 2,
                    'Романэ мануша': 2, 'Sel': 2, 'Sudutni Asiya': 2, 'Pakistan': 2, 'Indiya': 2,
                    'Mashkarutne Indo-Ariyane chhiba': 2, 'Shuto Orizari': 2, 'Republika Makedoniya': 2, 'Gav': 2,
                    'Foro': 2, 'Budeshti': 2, 'Chhib': 2, 'Chave': 2, 'Rekshan': 2, 'Bharat': 2, 'Them': 2,
                    'Extindere': 2, 'Jermaniya': 2, 'Bari Britaniya': 2, 'Spaniya': 2, 'Norvejiya': 2,
                    'Valshenengi Romani chhib': 2, 'Standardizuyimi Romani qhib (Selahetin Kruezi)': 2, 'Bulgariya': 2,
                    'Rusiya': 2, 'Rumuniya': 2, 'Chexiya': 2, 'Ungariya': 2, 'Nicolaye Gyorge': 2,
                    'Viktoriya Mohaci': 2, 'Liviya Yaroka': 2, 'Cedomir Yovanovic': 2, 'Shtefan Răzvan': 2,
                    'Yanosh Bogdan': 2, 'Raiko Juric': 2, 'Deliya Grigore': 2, 'Selahetin Kruezi': 2, 'Ronald Lee': 2,
                    'Mateo Maximoff': 2, 'Hedina Siyercic': 2, 'Katarina Taikon': 2, 'Vasile Yonesko': 2,
                    'Grigorash Diniku': 2, 'Django Reinhardt': 2, 'Yon Voiku': 2, 'Romika Puchanu': 2,
                    'Esma Rejepova': 2, 'Azis': 2, 'Sandro': 2, 'Shaban Bayramovic': 2, 'Reyhan': 2, 'Sofi Marinova': 2,
                    'Vali Vizheliye': 2, 'Adriyan Minune': 2, 'Zvonko Demirovic': 2, 'Fazliya': 2,
                    'Haso Menovin Frohlish': 2, 'Zhean Konstantin': 2, 'Shtefan Bǎnikǎ': 2, 'Xoakin Kortes': 2,
                    'Valery Novoselsky': 2, 'Johann Trollmann': 2, 'Rosa Taikon': 2, 'Ćhiba le romenge': 2,
                    "Sikingro'Kher": 2, 'Europa': 2, 'Romano siklyaripen la Rumuniyatar': 2,
                    'Romano siklyaripen le Slovaikostar': 2, 'Romano siklyaripen la Ungariyatar': 2, 'Franchiya': 2,
                    'Portugaliya': 2, 'Indo-Europikane chhiba': 2, 'Barodvip': 2, 'Andalusiya': 2, 'Kalo': 2,
                    'Chhiba le romenge': 2, 'Shelbersh': 2, 'Italiya': 2, 'Transilvaniya': 2, 'Slovakiya': 2,
                    'Manush': 2, 'Nasho': 2, 'Phuv': 2, 'Nordutni Amerika': 2, 'ABCD': 2, 'Seloro': 2, 'Romani': 2,
                    'Jegeya': 2, 'Chexay': 2, 'Shiyaron': 2, 'Samodor': 2, 'Phuvipnaske patrinimata': 2,
                    'Chhibavipnaski familiya': 2, 'Abejar': 3, 'Adradas': 3, 'Alconaba': 3,
                    'Alcubilla de Avellaneda': 3, 'Alcubilla de las Peñas': 3, 'Aldealafuente': 3, 'Aldealices': 3,
                    'Aldealpozo': 3, 'Aldealseñor': 3, 'Aldehuela de Periáñez': 3, 'Alentisque': 3, 'Aliud': 3,
                    'Almajano': 3, 'Almaluez': 3, 'Almarza': 3, 'Almazul': 3, 'Almazán': 3, 'Almenar de Soria': 3,
                    'Alpanseque': 3, 'Arancón': 3, 'Arcos de Jalón': 3, 'Arenillas': 3, 'Arévalo de la Sierra': 3,
                    'Ausejo de la Sierra': 3, 'Aven Amentza': 3, 'Baraona': 3, 'Barca': 3, 'Baro Belfast': 3, 'Bech': 3,
                    'Britanikane dvipa': 3, 'Chalga': 3, 'Chexiko stago (fana)': 3, 'Chhib (korposki)': 3,
                    'Chhibavipen': 3, 'Chhon (bersheski)': 3, 'Curitiba': 3, 'Diskriminaciya': 3, 'Drom': 3,
                    'Europako Romano Chachimasko Chentro': 3, 'Euroroma': 3, 'Finland': 3, 'Grazhduri': 3, 'Kanada': 3,
                    'Kher': 3, 'Kolombiya': 3, 'Kontinento': 3, 'Lakh': 3, 'Las Aldehuelas': 3, 'Luksemburgo': 3,
                    'Mahatma Gandhi': 3, 'Mesto software': 3, 'Partida le Romenge': 3,
                    'Patrinipen le bareder forutne umalurya la Indiyake': 3,
                    'Patrinipen le themengo kai o sherutno foro nai o bareder foro': 3, 'Polska': 3, 'Romanipen': 3,
                    'Shkiperiya': 3, 'Sofiya': 3, 'Thagaripen Inka': 3, 'Thanipen': 3,
                    'Themeski Ajenciya le Romengi (Rumuniyatar)': 3,
                    'Themesko Dives vash o Poraimosko Astaripen pe Godyate (la Rumuniyatar)': 3, 'Themutnipen': 3,
                    'Yashi': 3, 'Zhudetso Yashi': 3, 'Ágreda': 3, 'London': 3, 'Gelem, Gelem': 3, 'Afrika': 3,
                    'Sahel': 3, 'Sudutni Amerika': 3, 'Eurasiya': 3,
                    'Khetanipen la Sudutne Asiyako vash o Perutno Somkerdipen': 3, 'Styago Pakistan': 3,
                    'Stema Pakistan': 3, 'Than Pakistan': 3, 'Sherutno foro': 3,
                    'Patrinipen le themengo thai le durutne umalengo palal lengo baripen': 3,
                    'Patrinipen le themengo palal o gin le manushengo': 3,
                    'Patrinipen le themengo palal o butvaripen le manushengo': 3,
                    'Patrinipen le themengo palal o indekso le manushutne baryaripnasko': 3,
                    'Styago Bharat (Indiya)': 3, 'Stema Bharat (Indiya)': 3, 'Than Bharat (Indiya)': 3, 'Bombay': 3,
                    'Patrinimos le nacyonalne ćhibyango andi Indiya': 3, 'Bersh': 3,
                    'Staturya thai teritorurya la Indiyake': 3, 'Romani chhib': 3, 'Skopiye': 3,
                    'Styago Ketnepen Makedoniya': 3, 'Than Ketnepen Makedoniya': 3, 'Ketnepen': 3,
                    'Styago le Europikane Ekipnasko': 3, 'Europikano Ekipen': 3,
                    'Buxlyarimos le Europikane Ekipnasko': 3, 'Austriya': 3,
                    'Phandlo Thagaripen la Bare Britaniyako thai le Nordutne Irlandesko': 3, 'Beljiya': 3,
                    'Danemarka': 3, 'Estoniya': 3, 'Grechiya': 3, 'Republika Irland': 3, 'Latviya': 3, 'Lituaniya': 3,
                    'Malta': 3, 'Olanda': 3, 'Slovaiko': 3, 'Turkiya': 3, 'Patrinipen le themengo': 3, 'Andorra': 3,
                    'Elveciya': 3, 'Moldova': 3, 'Ukraina': 3, 'Vatican': 3, 'Dvipa Faroe': 3, 'Zhudetso': 3,
                    'Rumunikani ćhib': 3, 'Bukureshti': 3,
                    'Patrinipen le thanimatengo la Rumuniyake kai beshen but roma': 3, 'Chave Xrayen ando Indiya.': 3,
                    'Stato': 3, 'Shagede': 3, 'Styago Jermaniya': 3, 'Stema Jermaniya': 3, 'Than Jermaniya': 3,
                    'Berlin': 3, 'Jermanikani chib': 3, 'Phandlo Thagaripen': 3, 'Derya': 3, 'Paxro': 3, 'Dvip': 3,
                    'Styago Norvejiya': 3, 'Stema Norvejiya': 3, 'Than Norvejiya': 3, 'OTNA': 3, 'Styago Bulgariya': 3,
                    'Stema Bulgariya': 3, 'Than Bulgariya': 3, 'Otomano Thagaripen': 3, 'Styago _Rusiya': 3,
                    'Stema _Rusiya': 3, 'Than _Rusiya': 3, 'Rusikani chhib': 3, 'Rusikanes': 3,
                    'Styago VESSZEN TRIANON!': 3, 'Stema VESSZEN TRIANON!': 3, 'Than VESSZEN TRIANON!': 3,
                    'Bukureshta': 3, 'Thema la sundalake': 3, 'Styago Chexiya': 3, 'Stema Chexiya': 3,
                    'Than Chexiya': 3, 'Praga': 3, 'Romani ćhib': 3, 'Styago Ungariya': 3, 'Stema Ungariya': 3,
                    'Than Ungariya': 3, 'Peshta': 3, 'Ungarikani chib': 3, 'Rumunikanes': 3, 'Rom': 3, 'Romni': 3,
                    'Gandhi (mashkarutni shkola ando Pech)': 3, 'Pech': 3, 'Romanes': 3, 'Romano': 3,
                    'Rumunikano lekhipen': 3, 'Arxentina': 3, 'Menix': 3, 'Madrid': 3, 'Flamenko': 3, 'Israel': 3,
                    'Roma Virtual Network': 3, 'Gandhiskri shkola (Zvolenostar)': 3, 'Styago Fransiya': 3,
                    'Stema Fransiya': 3, 'Than Fransiya': 3, 'Paris': 3, 'Córdoba, Spaniya': 3, 'Styago Slovayko': 3,
                    'Stema Slovayko': 3, 'Nad Tatrou sa blýska': 3, 'Than Slovayko': 3, 'Vasho': 3, 'Shero': 3,
                    'Dimashko': 3, 'Kham-Sestemi': 3, 'Zaro': 3, 'Kham': 3, 'Budor': 3, 'Shukor': 3, 'Manjor': 3,
                    'Kuror': 3, 'Shani': 3, 'Rahor': 3, 'Ketor': 3, 'Pharnovon': 3,
                    'Patrinipen le dvipengo palal o baripen': 3, 'Angluni chhib': 3, 'Korkori chhib': 3,
                    'Chhibavipnasko azbalipen': 3, 'Xamome chhiba': 3, 'Patrinipen le chhibavipnaske familiyengo': 3,
                    'Soriya (provinciya)': 4, 'Belfast': 4, 'Nordutno Irland': 4, 'Stema le foroski Wien Vinya': 4,
                    'Wien Vinya andi Austriya': 4,
                    'Phandlo Thagaripen la Bari Britaniyako thai le Nordutne Irlandesko': 4, 'Xapen': 4, 'Brazil': 4,
                    'Styago Finland': 4, 'Stema Finland': 4, 'Than Finland': 4, 'Indo-Aryano': 4, 'Bogotá': 4,
                    'Ekuador': 4, 'Boliviya': 4, 'Chile': 4, 'Paraguay': 4, 'Peru': 4, 'Uruguay': 4, 'Venezuela': 4,
                    'Mumbai': 4, 'Devanagari': 4, 'Patrinipen le bareder forurengo la Indiyake': 4,
                    'Washington, D.C.': 4, 'New York City': 4, 'Brasília': 4, 'Ho Chi Minh City': 4,
                    'Indiya (Bharat)': 4, 'Styago Shkiperiya': 4, 'Stema Shkiperiya': 4, 'Than Shkiperiya': 4,
                    'Stema le foroski София/Sofia Sofiya': 4, 'София/Sofia Sofiya andi Bulgariya': 4, 'PhSA': 4,
                    'Deshbersh le Romengo Anderyaripnasko': 4, 'Rumunikani chhib': 4, 'Stema le foroski Iaşi Yashi': 4,
                    'Iaşi Yashi andi Rumuniya': 4, 'Zanya': 4, 'Butvaripen le manushengo': 4,
                    'Kalo-Derya Antalya Kemer Adrasan Saheliya': 4, 'Thema somdasne (membrurya) ando KhSAPS': 4,
                    'Bangladesh': 4, 'Sri Lanka': 4, 'Afghanistan': 4, 'Nepal': 4, 'Maldives': 4, 'Bhutan': 4,
                    'Manushutni Republika Kina': 4, 'Japan': 4, 'Phandle Staturya la Amerikyake': 4,
                    'Patrinipen le themengo le buteder sherutne forurenca': 4, 'Patrinipen le sherutne forurengo': 4,
                    'Argentina': 4, 'Mexico': 4, 'Ecuador': 4, 'Guatemala': 4, 'Slovakia': 4,
                    'Phandle Staturya la Amerikiyake': 4, 'Sudutni Koreya': 4, 'Kolumbiya': 4, 'Nordutni Koreya': 4,
                    'Kuba': 4, 'Palestina': 4, 'Lithuaniya': 4, 'Indekso le manushutne baryaripnasko': 4, 'Island': 4,
                    'Australiya': 4, 'Svedo': 4, 'Svicra': 4, 'Irland': 4, 'Phandle Staturya': 4, 'Oland': 4,
                    'Danemark': 4, 'Estrexa': 4, 'Nevo Zeyeland': 4, 'Hong Kong': 4, 'Republika China': 4,
                    'Singapore': 4, 'Sloveniya': 4, 'Republika Korea': 4, 'Chipro': 4, 'Barbados': 4,
                    'Flag of Libyan Arab Jamahiriya': 4, 'Flag of Samoa (Western)': 4,
                    'Flag of Islamic Republic of Iran': 4, 'Flag of Georgia': 4,
                    'Flag of Palestinian National Authority': 4, 'Flag of Syrian Arab Republic': 4,
                    'Flag of Viet Nam': 4, 'Flag of Republic of Moldova': 4, 'Flag of São Tomé and Principe': 4,
                    "Flag of Lao People's Democratic Republic": 4, 'Kongo': 4, 'Flag of Gambia': 4,
                    'Flag of United Republic of Tanzania': 4, 'Demokratikani Republika Kongo': 4,
                    "Flag of Democratic People's Republic of Korea": 4, 'Flag of Macau, China': 4,
                    'Distrikturya la Indiyake': 4, 'Patrinipen le distrikturengo la Indiyake': 4,
                    'Ekhipnasko Teritoryo': 4, 'Than': 4, 'Riga': 4, 'Yelenistan': 4, 'Letoniya': 4,
                    'Styago Phandlo Thagaripen la Bari Britaniyako tay le Nordutne Irlandesko': 4,
                    'Stema Phandlo Thagaripen la Bari Britaniyako tay le Nordutne Irlandesko': 4,
                    'Than Phandlo Thagaripen la Bari Britaniyako tay le Nordutne Irlandesko': 4, 'Irland (dvip)': 4,
                    'Styago Thangaripen Beljiyako': 4, 'Stema Thangaripen Beljiyako': 4,
                    'Than Thangaripen Beljiyako': 4, 'Brusel': 4, 'Styago Estoniya': 4, 'Stema Estoniya': 4,
                    'Than Estoniya': 4, 'Tallinn': 4, 'Stema Ketnepen Galyero': 4, 'Than Ketnepen Galyero': 4,
                    'Styago Latviya': 4, 'Stema Latviya': 4, 'Than Latviya': 4, 'Styago Lituaniya': 4,
                    'Stema Lituaniya': 4, 'Than Lituaniya': 4, 'Styago Turkiya': 4, 'Stema Turkiya': 4,
                    'Than Turkiya': 4, 'China': 4, 'Mêsire': 4, 'Styago Andorra': 4, 'Stema Andorra': 4,
                    'Than Andorra': 4, 'Styago Elvesiya': 4, 'Stema Elvesiya': 4, 'Than Elvesiya': 4,
                    'Styago Ukrayna': 4, 'Stema Ukrayna': 4, 'Than Ukrayna': 4, 'Kiev': 4,
                    'Administrative map of Romania': 4, 'Romanikane chhiba': 4, 'Latinikano lekhipen': 4,
                    'Vikipidiya': 4, 'Stema le foroski Bucureşti Bukureshti': 4,
                    'Bucureşti Bukureshti andi Rumuniya': 4, 'Daki chib': 4, 'Okeyanu': 4, 'Osmano Thagaripen': 4,
                    'Slavikane chhiba': 4, 'Krimeya': 4, 'Uralikane chhiba': 4, 'Stema le foroski Pécs Pech': 4,
                    'Pécs Pech andi Makyarestan': 4, 'Buenos Aires': 4, 'Zvolen': 4,
                    'Kham-Sestemi tay Le Oxtar Shiyaronuria': 4, 'Greenland': 4, 'Indoneziya': 4,
                    'Papua Nevi Guineya': 4, 'Brunei': 4, 'Malaysiya': 4, 'Madagaskar': 4, 'Filipine': 4,
                    'Dominikani Republika': 4, 'Haiti': 4, 'Timor-Leste': 4, 'Jamaika': 4, 'Fiji': 4,
                    'Turkish Republic of Northern Cyprus': 4, 'Puerto Rico': 4, 'Greece': 4, 'Canada': 4, 'France': 4,
                    'Trinidad and Tobago': 4, 'Vanuatu': 4, 'Spain': 4, 'Yemen': 4, 'Bahamas': 4, 'Cuba': 4,
                    'Colombia': 4, 'Equatorial Guinea': 4, 'Mauritius': 4, 'Myanmar': 4, 'Senegal': 4, 'Comoros': 4,
                    'French Polynesia': 4, 'Cape Verde': 4, 'Portugal': 4, 'Dominica': 4, 'Åland': 4, 'Kuwait': 4,
                    'Saint Lucia': 4, 'Bahrain': 4, 'Isle of Man': 4, 'Thailand': 4, 'Guam': 4, 'Costa Rica': 4,
                    'Tunisia': 4, 'Netherlands Antilles': 4, 'Croatia': 4, 'Kiribati': 4, 'Palau': 4,
                    'Saint Vincent and the Grenadines': 4, 'Federated States of Micronesia': 4, 'Grenada': 4,
                    'Antigua and Barbuda': 4, 'Tonga': 4, 'Italy': 4, 'Aruba': 4, 'Saint Kitts and Nevis': 4,
                    'Seychelles': 4, 'American Samoa': 4, 'Montserrat': 4, 'Saint Helena': 4, 'Jersey': 4,
                    'Chhibavipnaske familiye': 4, 'Korkore chhiba': 4, 'Soriya': 5,
                    'Stema le foroski Belfast Béal Feirste': 5, 'Belfast Béal Feirste andi Phandlo Thagaripen': 5,
                    'Than le Nordutno Irlandesko': 5, 'Nordutno Irlandesko than ando PhTh': 5, 'Santiago, Chile': 5,
                    'Styago Pero': 5, 'Stema Pero': 5, 'Than Pero': 5, 'Lima': 5, 'Montevideo': 5,
                    'Ho Chi Minh City Ho Chi Minh City andi Vietnam': 5, 'Valparaíso': 5, 'Lisbon': 5, 'Taluk': 5,
                    'Tehsil': 5, 'Stema le foroski Tallinn': 5, 'Tallinn andi Estoniya': 5, 'Asia': 5,
                    'Stema le foroski Kyiv Київ': 5, 'Xulavipen le Slavikane chhibango': 5, 'Styago la Krimeyako': 5,
                    'Stema la Krimeyako': 5, 'Than la Krimeyako': 5, 'Than la Krimeyako andi Rusiya': 5,
                    'Than la Krimeyako andi Ukraina': 5, 'Prinjardi chhib': 5,
                    'Patrinipen le internetoske umalurengo (TLD)': 5, 'Kali Deryav': 5, 'Subdivisions of Crimea': 5,
                    'Stema le foroski Zvolen Altsohl, Zólyom': 5, 'Zvolen Altsohl, Zólyom andi Slovakiya': 5}
